name: alin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21527156815864146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#434343'
    - '#676767'
    - '#c3c3c3'
    - '#ededed'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
